<!-- 
    Constants are unchangable values, for example, the speed of light in a vacuum is a constant value that never 
    changed. Other constants can include the density of lead per square inch, or something else that does not change.

    We use the define method to create a constant.

    It is worth noting that constants can not contain Boolean (true or false) Null (empty values) or Objects.
-->
<?php
    // We will create a constant for the speed of light.
    define ('C', 299792458);
    define ('units', 'meters per second');
    define ('C', 300000000); // We attempt to redefine what C is, the message generated by PHP in the browser is
    // Notice: Constant C already defined in C:\Program Files\Ampps\www\phpfundamentals\1.6 Variables and Constants\8 Creating constants.php on line 13
?>

<!doctype html>

<html lang=en>

<head>
    <title>What is Speed of light?</title>
</head>

<body>
    <head>
        <h1>What is Speed of light?</h1>
    </head>
    <main>
            <?php
                echo "<p>"; // We echo a paragraph start tag.
                print "The speed of light is ".C." ".units; // We add the first lower case name, to get a result.
                echo "</p>"; // We close the PHP tag.
                // You will notice that despite using the same word, using different cases makes each unique.
            ?>
    </main>
    <footer>
        <p>Copyright &copy; Daniel Foreman 2022, all rights reserved</p>
    </footer>
</body>

</html>